"""Discord environment variable names."""

from __future__ import annotations

DISCORD_BOT_TOKEN_ENV = "DISCORD_BOT_TOKEN"
DISCORD_APPLICATION_ID_ENV = "DISCORD_APPLICATION_ID"
DISCORD_PUBLIC_KEY_ENV = "DISCORD_PUBLIC_KEY"
DISCORD_DEFAULT_CHANNEL_ID_ENV = "DISCORD_DEFAULT_CHANNEL_ID"

__all__ = [
    "DISCORD_APPLICATION_ID_ENV",
    "DISCORD_BOT_TOKEN_ENV",
    "DISCORD_DEFAULT_CHANNEL_ID_ENV",
    "DISCORD_PUBLIC_KEY_ENV",
]
